name: CI
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    name: '${{ matrix.os.name}} | Java ${{ matrix.java.version}}'
    runs-on: ${{ matrix.os.id }}
    if: ${{ github.repository == 'spring-projects/spring-boot' || github.repository == 'spring-projects/spring-boot-commercial' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - id: ${{ vars.UBUNTU_MEDIUM || 'ubuntu-latest' }}
            name: Linux
          - id: windows-latest
            name: Windows
        java:
          - version: 17
            toolchain: false
          - version: 21
            toolchain: false
          - version: 22
            toolchain: false
          - version: 23
            toolchain: true
        exclude:
          - os:
              name: Linux
            java:
              version: 17
    steps:
      - name: Prepare Windows runner
        if: ${{ runner.os == 'Windows' }}
        run: |
          git config --global core.autocrlf true
          git config --global core.longPaths true
          Stop-Service -name Docker
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java.version }}
          java-early-access: ${{ matrix.java.early-access || 'false' }}
          java-toolchain: ${{ matrix.java.toolchain }}
          java-distribution: ${{ matrix.java.distribution }}
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          commercial-repository-username: ${{ secrets.COMMERCIAL_ARTIFACTORY_RO_USERNAME }}
          commercial-repository-password: ${{ secrets.COMMERCIAL_ARTIFACTORY_RO_PASSWORD }}
          commercial-release-repository-url: ${{ vars.COMMERCIAL_RELEASE_REPO_URL }}
          commercial-snapshot-repository-url: ${{ vars.COMMERCIAL_SNAPSHOT_REPO_URL }}
      - name: Send Notification
        uses: ./.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          status: ${{ job.status }}
          build-scan-url: ${{ steps.build.outputs.build-scan-url }}
          run-name: ${{ format('{0} | {1} | Java {2}', github.ref_name, matrix.os.name, matrix.java.version) }}
